---
# This YAML file is used to store configuration parameter for CopyCat backend.
# For a more detailed explanation of each parameter, please refer to CopyCat backend documentation.
# Format is follow YAML standard.

# Load Balancer
loadBalancer : 'CopyCatLoadBalancer-426137485.us-east-1.elb.amazonaws.com'

# MongoDB replica set address
replicaAddr: !!seq
- '172.31.59.129:27017'
- '172.31.49.28:27017'
- '172.31.18.73:27017'

# AWS credential
credential: !!map
  accessKeyId: AKIAIMLE76URPMCTIAXA
  secretAccessKey: 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
  region: us-east-1

# server port
httpPort: 80
httpDevPort: 3000
httpsPort: 443

# s3 image bucket name
s3ImageBucket: !!map
  name: copycatimage

# instagram
instagram: !!map
  clientId: 'ea2679a4073c4809919836b18e91b257'
  clientSecret : '87e2890a23fd4defb7fc2cfc76f43d15'
  grantType : 'authorization_code'
  redirectURL: 'http://copycatloadbalancer-426137485.us-east-1.elb.amazonaws.com/api/v0/instagram/login'

# test secret code
secret: 'copycattest'
copycattestId: '5737e97e0c7956dc7d4ada47'

# compress parameter
maxWidth: 800
maxHeight: 800

# user
anonymousUserName: 'anonymous'
anonymousProfilePictureUrl: 'https://pbs.twimg.com/profile_images/471316589996806145/0oKVzgtV.jpeg'
  
# google cloud vision api key
cloudVisionApiKey: 'AIzaSyA8WAYHLpgXjB2ajsgscSiFlOl05-lTvEA'

